name: Build and Deploy Next.js App to Azure

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22.x'

            - name: Deploy to Azure Web App (via Oryx)
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'son-eus2-proforma-app01'
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
